# This is a basic workflow to help you get started with Actions

name: Build squeekboard

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "testing" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build deb packages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: testing
      
      - name: QEMU set-up
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Pull container
        run: docker pull quay.io/droidian/build-essential:bookworm-arm64

      - name: Start Container
        run: echo CONTAINER_HASH=$(docker run -dt --privileged --platform linux/arm64 -v ${PWD}:/buildd/sources quay.io/droidian/build-essential:bookworm-arm64) >> $GITHUB_ENV

      - name: Build squeekboard
        run: |
          docker exec $CONTAINER_HASH bash -c "cd /buildd/sources && 
                                                    apt update && 
                                                    mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control && 
                                                    rm -f squeekboard-build-deps_*.* && 
                                                    dpkg-buildpackage -us -uc -b"
          
      - name: Copy packages to out directory
        run: |
          mkdir out
          cp ../*.deb out/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: squeekboard
          path: out/*.deb
          if-no-files-found: error
          retention-days: 1

  prepare:
    runs-on: ubuntu-latest
    name: Create GitHub release
    needs: build

    steps:
      - name: Delete old latest release
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest

  publish:
    runs-on: ubuntu-latest
    needs: prepare

    name: Publish squeekboard

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: out

      - name: Create latest release
        uses: softprops/action-gh-release@v1
        with:
          files: out/squeekboard/*.deb
          tag_name: latest
          draft: false
          prerelease: false
